### PR TITLE
Tictec january changes

### PR DESCRIPTION
**Pull request by ajparsons**
Gemma's requested changes for review.

Additional change: I made it so that the default blocks are generated if absent to make setting up new vagrants easier if you don't have access to the main database.

### CODE REVIEW

**Review by chrismytton — APPROVED** [review]
Thanks @ajparsons, looks good to me! ✨ 

My only minor comment is that the extra nav items mean the log in link (or currently logged in user's email address, if they're already logged in) gets pushed onto a new line. However I'm not sure how many non-mySociety people actually log into the site, perhaps we can simply remove the log in link/email address bit? Either way I don't think that's a blocker, so I'll get this merged now.

## Log in link

image

## Logged in user's email

image

**Comment by chrismytton** [comment]
> Additional change: I made it so that the default blocks are generated if absent to make setting up new vagrants easier if you don't have access to the main database.

FYI you can use `script/mirror-live-database` to mirror the live database. (But adding the blocks in by default is definitely a good idea! Will make it easier if/when we add new blocks.)

**Comment by chrismytton** [comment]
This is now live 👉  https://tictec.mysociety.org/

**Comment by ajparsons** [comment]
> FYI you can use `script/mirror-live-database` to mirror the live database. (But adding the blocks in by default is definitely a good idea! Will make it easier if/when we add new blocks.)

Yeah saw that but it seemed like I wasn't going to be able to figure it out quickly in a Windows host machine (but in principle is good!).

**Pull request merged**
