### PR TITLE
Vagrant adaptions

### PR DESCRIPTION
**Pull request by ajparsons**
Migrated some of the adaptions I've made to the research repository vagrant and possibly addressed speed issue:

- Makes repo function better on windows (enforces unix line endings)
- Change so site-packages are not stored on host and fixes permission issue that causes (based on Chris's comment on what Sam had done to speed up another repo - big speed difference on windows, but might be another reason this is done the way it is)
- Changes starting directory of vagrant
- Adds script-to-rule-them-all to start without having to specific source

This seems to get to a working state from scratch, but I don't have a source of data to test on. Will probably need existing vagrants to be recreated.

### CODE REVIEW

**Comment by sagepe** [comment]
On a clean clone, I get an error when trying to load the sample data during the `vagrant up`:
```
Problem installing fixture '/vagrant/ainow/conference/fixtures/sample-data.json': [u"'10:00:00' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]: #(conference.slot:pk=1) field_value was '10:00:00'
```
Given #139, perhaps this is a red herring as I don't think that this is useful for Tictec anyway?

**Comment by ajparsons** [comment]
Yeah, I think loading those fixtures is in the plan to go anyway - don't think it reflects on these changes as much.

**Comment by chrismytton** [comment]
> On a clean clone, I get an error when trying to load the sample data during the `vagrant up`:
> 
> ```
> Problem installing fixture '/vagrant/ainow/conference/fixtures/sample-data.json': [u"'10:00:00' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]: #(conference.slot:pk=1) field_value was '10:00:00'
> ```
> 
> Given #139, perhaps this is a red herring as I don't think that this is useful for Tictec anyway?

Yeah I got the same error. I think these fixtures can simply be deleted and that line of the provisioning removed. We want to load a copy of the live database anyway, so no point in loading other things into the DB first.

**Comment by ajparsons** [comment]
Those fixtures have been removed - no errors now until you actually load it and it doesn't have data.

**Comment by sagepe** [comment]
I think this can probably be merged then, and the missing data handled in #139.

**Review by sagepe — APPROVED** [review]

**Pull request merged**
