### PR TITLE
Show and Tells 2021

### PR DESCRIPTION
**Pull request by zarino**
@Gemmamysoc Here’s how it’s looking so far:

Screenshot_2021-01-05 TICTeC Show and Tells 2021 TICTeC

The "What to include in your proposal" section starts off collapsed, and you can open it by clicking the heading, as you’d expect.

Screenshot_2021-01-05 TICTeC Show and Tells 2021 TICTeC(1)

What image do you think we should use in the header?

### CODE REVIEW

**Comment by Gemmamysoc** [comment]
Cheers @zarino. Looking good. I have some queries:

- Can 'Press Enquiries' be removed from the top menu bar please? It's out of date at the moment, so needs refresh, which I haven't had time to do yet.
- Can the 'What to include in your proposal' section be linked to? If so, what is the url? I want to link to that section from the Call for Proposals submission form etc. 
- In terms of header image maybe this one: https://www.flickr.com/photos/mysociety/37305111901/in/album-72157687147985193/?! I've always love that image
- Would it be much more hassle to add a quotes and photos section to the bottom of this page under the 'Sponsorship opportunities' section? A bit like at the bottom of this page: https://tictec.mysociety.org/2020? Just to jazz it up a bit? Could select images from here:
https://www.flickr.com/photos/mysociety/albums/with/72157666482366877 and I can give you some different quotes, if that's okay?

**Comment by Gemmamysoc** [comment]
Quotes for 'jazzy' section:

- "TICTeC was one of the most diverse conferences I’ve ever attended, not just in terms of gender, but also in terms of representativeness of regions of the world, plus a great variety of professional profiles and backgrounds."
- "I think TICTeC stands out as an example where it’s about the lessons learnt rather than the activities. The focus on ‘This is the impact we’ve uncovered by doing this project’ sets TICTeC apart."
- "TICTeC has been a great way for me personally as a relatively new person in the field to get exposure to new ideas, connect with incredibly helpful people, and to generally learn about new trends from around the world.””
- "TICTeC worked well as a virtual event because you felt like everyone involved was 'in the room' and participating. It was the closest I've come to having an online event 'feel' like a real life event."

**Comment by zarino** [comment]
> • Can 'Press Enquiries' be removed from the top menu bar please? It's out of date at the moment, so needs refresh, which I haven't had time to do yet.

Done now!

> • Can the 'What to include in your proposal' section be linked to? If so, what is the url? I want to link to that section from the Call for Proposals submission form etc.

Yes, once this has been deployed, linking to https://tictec.mysociety.org/showandtells/2021#guidance will jump the user down to that section, and automatically unfold the hidden guidance element.

> • Would it be much more hassle to add a quotes and photos section…

Done. How’s this?

Screenshot_2021-01-06 TICTeC Show and Tells 2021 TICTeC

**Comment by Gemmamysoc** [comment]
I replied to this via email yesterday but it seems to have gone into the ether!! Marvellous, thanks very much. Please could you make the 20 April date and the 25 May date GMT+1, rather than just GMT? Also, is [this document](https://github.com/mysociety/ainow/files/5786305/TICTeC.2021.Sponsorship.Opportunities.pdf) linked to from the 'sponsorship options' bit in the Sponsorship opportunities section? 

And can you make and deploy the [changes to the Sponsorship page](https://docs.google.com/document/d/1gqI-LhBkiQOICkteD4g13Yo9DT2Tm84bQbC1vlBYiII/edit#bookmark=id.tvpterug98a) too please?

Thanks so much!

**Comment by zarino** [comment]
> Please could you make the 20 April date and the 25 May date GMT+1, rather than just GMT? Also, is this document linked to from the 'sponsorship options' bit in the Sponsorship opportunities section?

Done and done.

> And can you make and deploy the changes to the Sponsorship page too please?

This pull request already includes the changes to the Sponsorship page. https://github.com/mysociety/ainow/pull/167/files#diff-2efafe400fae24fb6409845a688c2fb9b5aea39a8829d15be4068fcaf025165bL88-R88

**Pull request merged**
