### PR TITLE
Add Balsamiq as new sponsor for 2020

### PR DESCRIPTION
**Pull request by wrightmartin**

### CODE REVIEW

**Comment by wrightmartin** [comment]
image

**Comment by Gemmamysoc** [comment]
@wrightmartin any way Balsamiq's logo could be smaller than Luminate's? cheers

**Comment by wrightmartin** [comment]
Yep - have made it so it will always be smaller

image

**Review by chrismytton — APPROVED** [review]

**Comment by chrismytton** [comment]
This is now live: https://tictec.mysociety.org/2020

**Comment by Gemmamysoc** [comment]
Thanks both :)

**Pull request merged**
